apiVersion: k8s-operator.alluxio.com/v1
kind: AlluxioCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.global.azure.images.enterprise.registry }}/{{ .Values.global.azure.images.enterprise.image }}
  imageTag: {{ .Values.global.azure.images.enterprise.tag }}
  
  properties:
    alluxio.user.fuse.random.access.file.stream.enabled: "true"
    alluxio.license: {{ .Values.cluster.properties.licenseString | quote }}

  user: 0
  group: 0
  fsGroup: 0
  hostNetwork: true

  prometheus:
    tolerations:
      - operator: Exists
    image: {{ .Values.global.azure.images.prometheus.registry }}/{{ .Values.global.azure.images.prometheus.image }}
    imageTag: {{ .Values.global.azure.images.prometheus.tag }}
  
  grafana:
    tolerations:
      - operator: Exists
    ports:
      web: 3000
      hostPort: 3000
    image: {{ .Values.global.azure.images.grafana.registry }}/{{ .Values.global.azure.images.grafana.image }}
    imageTag: {{ .Values.global.azure.images.grafana.tag }}

  etcd:
    tolerations:
      - operator: Exists
    replicaCount: {{ .Values.cluster.etcd.replicaCount }}
    image:
      registry: {{ .Values.global.azure.images.etcd.registry }}
      repository: {{ .Values.global.azure.images.etcd.image }}
      tag: {{ .Values.global.azure.images.etcd.tag }}
    volumePermissions:
      image:
        registry: {{ .Values.global.azure.images.osshell.registry }}
        repository: {{ .Values.global.azure.images.osshell.image }}
        tag: {{ .Values.global.azure.images.osshell.tag }}
    persistence:
      enabled: {{ .Values.cluster.etcd.persistence.enabled }}
      storageClass: {{ .Values.cluster.etcd.persistence.storageClass }}
      size: {{ .Values.cluster.etcd.persistence.size }}

  coordinator:
    tolerations:
      - operator: Exists
    metastore:
      hostPath: /mnt/alluxio/master/meta
    resources:
      limits:
        cpu: {{ .Values.cluster.coordinator.resources.cpuLimit | quote }}
        memory: {{ .Values.cluster.coordinator.resources.memoryLimit | quote }}
      requests:
        cpu: {{ .Values.cluster.coordinator.resources.cpuRequest | quote }}
        memory: {{ .Values.cluster.coordinator.resources.memoryRequest | quote }}
    jvmOptions:
      - "-Xmx{{ .Values.cluster.coordinator.jvm.xmx }}"
      - "-Xms{{ .Values.cluster.coordinator.jvm.xms }}"
      - "-XX:MaxDirectMemorySize={{ .Values.cluster.coordinator.jvm.maxDirect }}"
        
  worker:
    count: {{ .Values.cluster.worker.count }}
    useExternalId: false
    systemInfo:
      type: hostPath
      hostPath: /mnt/alluxio/system-info
    log:
      type: hostPath
      hostPath: /mnt/alluxio/logs/worker
    metastore:
      type: hostPath
      hostPath: /mnt/alluxio/pagestore/meta

  workerGroups:
  - worker:
      tolerations:
        - operator: Exists
      count: {{ .Values.cluster.worker.count }} 
      pagestore:
        hostPath: {{ .Values.cluster.worker.pagestorePath }}
        size: {{ .Values.cluster.worker.pagestoreSize }} 
      resources:
        limits:
          cpu: {{ .Values.cluster.worker.resources.cpuLimit | quote }}
          memory: {{ .Values.cluster.worker.resources.memoryLimit | quote }}
        requests:
          cpu: {{ .Values.cluster.worker.resources.cpuRequest | quote }}
          memory: {{ .Values.cluster.worker.resources.memoryRequest | quote }}
      jvmOptions:
        - "-Xmx{{ .Values.cluster.worker.jvm.xmx }}"
        - "-Xms{{ .Values.cluster.worker.jvm.xms }}"
        - "-XX:MaxDirectMemorySize={{ .Values.cluster.worker.jvm.maxDirect }}"

  fuse:
    tolerations:
      - operator: Exists
    type: csi
    env: {} 
    resources:
      limits:
        cpu: {{ .Values.cluster.fuse.resources.cpuLimit | quote }}
        memory: {{ .Values.cluster.fuse.resources.memoryLimit | quote }}
      requests:
        cpu: {{ .Values.cluster.fuse.resources.cpuRequest | quote }}
        memory: {{ .Values.cluster.fuse.resources.memoryRequest | quote }}
    jvmOptions: 
      - "-Xmx{{ .Values.cluster.fuse.jvm.xmx }}"
      - "-Xms{{ .Values.cluster.fuse.jvm.xms }}"
      - "-XX:MaxDirectMemorySize={{ .Values.cluster.fuse.jvm.maxDirect }}"
    mountOptions:
      - allow_other
      - kernel_cache
      - entry_timeout=30
      - attr_timeout=30
      - local_metadata_cache_size=0
      - max_background=2048
      - max_idle_threads=2048